name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Step — Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Step — Select correct Xcode version
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      # 3️⃣ Step — Build the project
      - name: Build the app
        run: |
          xcodebuild -project RevNewApp7Oct2025.xcodeproj \
          -scheme RevNewApp7Oct2025 \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          clean build
